# -*- coding: utf-8 -*-
"""Record lifecycles for the Odoo app pages (the "how a record moves" demo on every app page).

Each app: the record it manages, its states in order, the main path, branches (exceptions, loops),
hand-offs into other apps (fired on a state), and the automations TechNext configures. States are
the ones Odoo shows (Odoo 17 to 20), kept short. Layout per category gives each family of pages its
own visual form: rail · ladder · ring · funnel · board · hub · journey.

state: (key, label, note)
branch: (from, to, label)            -> an exception or loop off the main path
handoff: (state, app module, text)   -> fires when a record reaches that state
"""

LAYOUT = {"finance": "ladder", "sales": "rail", "websites": "journey", "supply-chain": "rail",
          "hr": "ring", "marketing": "funnel", "services": "board", "productivity": "hub"}

FLOWS = {
    # ------------------------------------------------------------------ finance
    "accountant": {"record": "bank statement line", "article": "a",
        "states": [("feed", "Imported", "Bank feed brings the line in"), ("match", "Matched", "Reconciliation rules propose the match"),
                   ("rec", "Reconciled", "Invoice or bill closed"), ("close", "Period closed", "Lock date set after the review"),
                   ("report", "Reported", "P&L, balance sheet, GST report")],
        "path": ["feed", "match", "rec", "close", "report"],
        "branches": [("match", "feed", "No match: manual search or write-off"), ("rec", "match", "Partial payment: open balance kept")],
        "handoffs": [("rec", "account", "Invoices and bills marked paid"), ("report", "spreadsheet_dashboard", "Finance dashboard refreshed")],
        "auto": ["Bank synchronisation where your bank supports it", "Reconciliation models for recurring lines", "Lock dates so closed months stay closed"]},
    "account": {"record": "customer invoice", "article": "a",
        "states": [("draft", "Draft", "Created from the sales order or by hand"), ("posted", "Posted", "Journal entry booked"),
                   ("sent", "Sent", "Emailed with a payment link"), ("inpay", "In payment", "Payment registered, waiting for the bank"),
                   ("paid", "Paid", "Matched on the bank statement")],
        "path": ["draft", "posted", "sent", "inpay", "paid"],
        "branches": [("sent", "sent", "Overdue: follow-up reminder sent"), ("posted", "draft", "Reset to draft to correct a mistake")],
        "handoffs": [("draft", "sale", "Invoiced quantities written back to the order"), ("paid", "accountant", "Receivable cleared in the ledger"),
                     ("sent", "mail", "Customer sees it in the portal")],
        "auto": ["Invoicing policy per product: on order or on delivery", "Follow-up levels for overdue invoices", "Online payment through your payment provider"]},
    "hr_expense": {"record": "expense", "article": "an",
        "states": [("draft", "Draft", "Receipt photographed, fields filled by OCR"), ("sub", "Submitted", "Sent to the manager"),
                   ("appr", "Approved", "Manager approves"), ("post", "Posted", "Journal entry booked"), ("paid", "Paid", "Reimbursed in a batch")],
        "path": ["draft", "sub", "appr", "post", "paid"],
        "branches": [("sub", "draft", "Refused: sent back with a reason")],
        "handoffs": [("post", "accountant", "Expense and employee payable booked"), ("appr", "sale", "Billable expense added to the sales order"),
                     ("paid", "hr", "Reimbursement recorded on the employee")],
        "auto": ["Expense categories with accounts and taxes", "Approval by the employee's manager", "Company card expenses that need no reimbursement"]},
    "spreadsheet_dashboard": {"record": "dashboard", "article": "a",
        "states": [("src", "Data source", "Pivot or list from any Odoo app"), ("sheet", "Spreadsheet", "Formulas on live Odoo data"),
                   ("dash", "Dashboard", "Published for a team"), ("share", "Shared", "Access by user group"), ("fresh", "Refreshed", "Always the latest data")],
        "path": ["src", "sheet", "dash", "share", "fresh"],
        "branches": [("fresh", "sheet", "New question: add a pivot, keep the sheet")],
        "handoffs": [("src", "sale", "Sales pivots"), ("src", "accountant", "Accounting figures"), ("src", "stock", "Stock levels")],
        "auto": ["Ready-made dashboards per app", "Global filters by period, company and team", "No exports to keep up to date"]},
    "documents": {"record": "document", "article": "a",
        "states": [("in", "Inbox", "Arrives by email alias, upload or scan"), ("tag", "Tagged", "Workspace and tags set"),
                   ("act", "Actioned", "Action run on the file"), ("link", "Linked", "Attached to its Odoo record"), ("arch", "Archived", "Kept, searchable")],
        "path": ["in", "tag", "act", "link", "arch"],
        "branches": [("act", "tag", "Split a PDF into separate documents"), ("tag", "arch", "Not needed: archived")],
        "handoffs": [("act", "account", "Vendor bill created and digitised"), ("act", "sign", "Signature requested"), ("link", "hr", "Filed on the employee")],
        "auto": ["Email aliases per workspace", "Workflow actions: create a bill, request a signature, move", "Access rules per workspace"]},
    "sign": {"record": "signature request", "article": "a",
        "states": [("draft", "Draft", "Template with signer roles"), ("sent", "Sent", "Email with a secure link"),
                   ("part", "Partially signed", "First signer done"), ("signed", "Fully signed", "Certificate and audit trail"), ("arch", "Archived", "Stored with the record")],
        "path": ["draft", "sent", "part", "signed", "arch"],
        "branches": [("sent", "draft", "Refused by a signer: corrected and resent"), ("sent", "sent", "Reminder sent")],
        "handoffs": [("signed", "sale", "Signed quotation confirms the order"), ("signed", "hr", "Signed contract filed on the employee"),
                     ("arch", "documents", "Signed PDF in Documents")],
        "auto": ["Templates with roles and fields", "Signing order for several signers", "Reminders until signed"]},
    # ------------------------------------------------------------------ sales
    "crm": {"record": "opportunity", "article": "an",
        "states": [("new", "New", "From a web form, email alias, chat or event list"), ("qual", "Qualified", "Need, budget and timing checked"),
                   ("prop", "Proposition", "Quotation sent"), ("won", "Won", "Deal closed"), ("lost", "Lost", "Reason recorded")],
        "path": ["new", "qual", "prop", "won"],
        "branches": [("qual", "lost", "Not a fit: lost reason logged"), ("prop", "qual", "Needs change: back to qualified"), ("prop", "lost", "Lost to a competitor")],
        "handoffs": [("won", "sale", "Quotation becomes a sales order"), ("new", "mass_mailing", "Added to a nurture list"), ("prop", "sign", "Quotation sent to sign")],
        "auto": ["Assignment rules by team and territory", "Lead scoring", "Scheduled activities per stage"]},
    "sale": {"record": "sales order", "article": "a",
        "states": [("quo", "Quotation", "From a template, with your pricelist"), ("sent", "Quotation sent", "Customer signs or pays online"),
                   ("so", "Sales order", "Confirmed, stock reserved"), ("dlv", "Delivered", "Warehouse validates the delivery"), ("inv", "Invoiced", "Invoice from delivered quantities")],
        "path": ["quo", "sent", "so", "dlv", "inv"],
        "branches": [("sent", "quo", "Customer asks for changes: new version"), ("sent", "sent", "Expired: reminder and new validity date")],
        "handoffs": [("so", "stock", "Delivery order created"), ("inv", "account", "Invoice posted"), ("so", "mrp", "Make to order: manufacturing order")],
        "auto": ["Quotation templates and optional products", "Online signature and payment", "Invoicing policy: on order or on delivery"]},
    "point_of_sale": {"record": "POS session", "article": "a",
        "states": [("open", "Opened", "Cash float counted"), ("sell", "Selling", "Orders paid by cash, card or wallet"),
                   ("clos", "Closing", "Cash control and differences"), ("post", "Posted", "One journal entry per session"), ("done", "Closed", "Stock and sales reported")],
        "path": ["open", "sell", "clos", "post", "done"],
        "branches": [("sell", "sell", "Refund or exchange at the till"), ("clos", "sell", "Difference found: recount")],
        "handoffs": [("sell", "stock", "Stock moves for every product sold"), ("post", "accountant", "Sales, payments and taxes posted"), ("sell", "crm", "Loyalty points on the customer")],
        "auto": ["Offline mode that syncs when back online", "Loyalty, promotions and gift cards", "Payment terminals and receipt printers"]},
    "pos_restaurant": {"record": "table order", "article": "a",
        "states": [("seat", "Seated", "Table opened on the floor plan"), ("order", "Ordered", "Sent to the kitchen display"),
                   ("serve", "Served", "Kitchen marks it ready"), ("bill", "Bill", "Split by seat or amount"), ("paid", "Paid", "Table free again")],
        "path": ["seat", "order", "serve", "bill", "paid"],
        "branches": [("serve", "order", "More dishes ordered"), ("bill", "bill", "Bill split between guests")],
        "handoffs": [("order", "mrp", "Recipe components deducted"), ("paid", "accountant", "Session posted at closing"), ("order", "stock", "Ingredient stock updated")],
        "auto": ["Floor plans with table status", "Preparation display per kitchen station", "Tips and split bills"]},
    "sale_subscription": {"record": "subscription", "article": "a",
        "states": [("quo", "Quotation", "Plan and recurrence chosen"), ("run", "In progress", "Recurring invoices raised"),
                   ("up", "Upsell", "Extra seats or options added"), ("renew", "To renew", "Renewal quotation sent"), ("churn", "Churned", "Closed with a reason")],
        "path": ["quo", "run", "up", "renew", "run"],
        "branches": [("run", "churn", "Cancelled by the customer"), ("renew", "churn", "Not renewed"), ("run", "run", "Payment failed: retried")],
        "handoffs": [("run", "account", "Invoice each period"), ("renew", "crm", "Renewal opportunity"), ("run", "spreadsheet_dashboard", "MRR and churn reported")],
        "auto": ["Recurring plans: monthly, yearly or custom", "Automatic payment with saved cards", "Health checks and closing reasons"]},
    "sale_renting": {"record": "rental order", "article": "a",
        "states": [("quo", "Quotation", "Rental period and pricing"), ("res", "Reserved", "Unit booked for the dates"),
                   ("pick", "Picked up", "Handed over, serial recorded"), ("ret", "Returned", "Checked back in"), ("inv", "Invoiced", "Rental and any extras billed")],
        "path": ["quo", "res", "pick", "ret", "inv"],
        "branches": [("pick", "pick", "Late return: late fee added"), ("ret", "ret", "Damage found: repair charged")],
        "handoffs": [("pick", "stock", "Unit moves out of stock"), ("inv", "account", "Invoice and deposit handled"), ("res", "sign", "Rental agreement signed")],
        "auto": ["Pricing per hour, day or week", "Availability calendar per product", "Deposits and late fees"]},
    # ------------------------------------------------------------------ websites
    "website": {"record": "visitor", "article": "a",
        "states": [("land", "Landing", "Arrives from search, social or email"), ("browse", "Browsing", "Pages tracked on the visitor"),
                   ("engage", "Engaged", "Chat, form or download"), ("lead", "Lead", "Created in CRM with the source"), ("cust", "Customer", "Order or signed quotation")],
        "path": ["land", "browse", "engage", "lead", "cust"],
        "branches": [("browse", "land", "Leaves, comes back from an email"), ("engage", "browse", "Reads more first")],
        "handoffs": [("lead", "crm", "Lead with UTM source and pages seen"), ("engage", "im_livechat", "Live chat started"), ("cust", "sale", "Quotation or order")],
        "auto": ["Forms that create leads, tickets or applicants", "Visitor tracking and UTM sources", "SEO fields per page"]},
    "website_sale": {"record": "web order", "article": "a",
        "states": [("cart", "Cart", "Products with live stock"), ("chk", "Checkout", "Address and delivery method"),
                   ("pay", "Paid", "Payment provider confirms"), ("so", "Order", "Sales order confirmed"), ("ship", "Shipped", "Delivery and tracking")],
        "path": ["cart", "chk", "pay", "so", "ship"],
        "branches": [("cart", "cart", "Abandoned: reminder email"), ("pay", "chk", "Payment failed: try another method")],
        "handoffs": [("so", "stock", "Stock reserved, delivery created"), ("so", "account", "Invoice after payment"), ("cart", "mass_mailing", "Cart recovery email")],
        "auto": ["Payment providers and delivery carriers", "Pricelists and promotions online", "Stock shown on the product page"]},
    "website_blog": {"record": "blog post", "article": "a",
        "states": [("draft", "Draft", "Written in the website editor"), ("seo", "Optimised", "Title, meta and cover set"),
                   ("pub", "Published", "Live on the blog"), ("promo", "Promoted", "Shared by email and social"), ("lead", "Leads", "Readers sign up or enquire")],
        "path": ["draft", "seo", "pub", "promo", "lead"],
        "branches": [("pub", "draft", "Update: edited and republished")],
        "handoffs": [("promo", "social", "Scheduled social posts"), ("promo", "mass_mailing", "Newsletter"), ("lead", "crm", "Leads from the post")],
        "auto": ["Scheduled publishing", "Tags and blog categories", "Visitor tracking to leads"]},
    "website_forum": {"record": "forum question", "article": "a",
        "states": [("ask", "Asked", "Posted by a user"), ("mod", "Moderated", "Checked by karma rules"), ("ans", "Answered", "Community or staff reply"),
                   ("acc", "Accepted", "Best answer marked"), ("karma", "Rewarded", "Karma and badges earned")],
        "path": ["ask", "mod", "ans", "acc", "karma"],
        "branches": [("mod", "ask", "Flagged: edited or closed"), ("ans", "ans", "More answers voted up")],
        "handoffs": [("ask", "helpdesk", "Unanswered question becomes a ticket"), ("acc", "knowledge", "Answer turned into an article")],
        "auto": ["Karma levels that unlock moderation", "Badges and votes", "Tags and duplicates merged"]},
    "im_livechat": {"record": "chat", "article": "a",
        "states": [("vis", "Visitor", "Browsing a page"), ("bot", "Chatbot", "Answers the first questions"), ("op", "Operator", "Handed to a person"),
                   ("conv", "Conversation", "Answered in Discuss"), ("rate", "Rated", "Visitor rates the chat")],
        "path": ["vis", "bot", "op", "conv", "rate"],
        "branches": [("bot", "rate", "Solved by the chatbot"), ("op", "op", "No operator: leave a message")],
        "handoffs": [("conv", "crm", "Lead created from the chat"), ("conv", "helpdesk", "Ticket created"), ("op", "mail", "Chat in Discuss")],
        "auto": ["Chatbot scripts", "Rules by page and country", "Canned responses"]},
    "website_slides": {"record": "course", "article": "a",
        "states": [("pub", "Published", "Course on the website"), ("enrol", "Enrolled", "Free, invited or paid"), ("learn", "Learning", "Lessons and videos"),
                   ("quiz", "Quizzed", "Quizzes per lesson"), ("cert", "Certified", "Certification passed")],
        "path": ["pub", "enrol", "learn", "quiz", "cert"],
        "branches": [("quiz", "learn", "Failed: retake the lesson")],
        "handoffs": [("enrol", "website_sale", "Paid course sold online"), ("cert", "survey", "Certification survey"), ("learn", "website_forum", "Course forum")],
        "auto": ["Paid or free courses", "Karma and badges", "Progress per attendee"]},
    # ------------------------------------------------------------------ supply chain
    "stock": {"record": "transfer", "article": "a",
        "states": [("rec", "Receipt", "Goods in from the vendor"), ("put", "Put away", "To the right location"), ("stk", "In stock", "Available to reserve"),
                   ("pick", "Picked", "By barcode"), ("ship", "Shipped", "Delivery validated")],
        "path": ["rec", "put", "stk", "pick", "ship"],
        "branches": [("pick", "stk", "Short pick: backorder created"), ("stk", "rec", "Below minimum: reordering rule")],
        "handoffs": [("stk", "purchase", "Reordering rule raises an RFQ"), ("ship", "account", "Invoice on delivered quantities"), ("rec", "quality_control", "Quality check on receipt")],
        "auto": ["Routes: one, two or three steps", "Reordering rules per warehouse", "Lots, serial numbers and expiry"]},
    "mrp": {"record": "manufacturing order", "article": "a",
        "states": [("draft", "Draft", "From demand or a reorder rule"), ("conf", "Confirmed", "Components reserved"), ("prog", "In progress", "Work orders at work centres"),
                   ("close", "To close", "Quantities produced"), ("done", "Done", "Finished goods in stock")],
        "path": ["draft", "conf", "prog", "close", "done"],
        "branches": [("prog", "prog", "Scrap recorded on a work order"), ("conf", "conf", "Waiting for components")],
        "handoffs": [("conf", "purchase", "Missing components ordered"), ("prog", "quality_control", "Quality checks on operations"), ("done", "accountant", "Production cost valued")],
        "auto": ["Multi-level bills of materials", "Work centres with capacity", "Backorders and by-products"]},
    "mrp_plm": {"record": "engineering change", "article": "an",
        "states": [("new", "New", "Change requested"), ("prog", "In progress", "New BoM version drafted"), ("appr", "To approve", "Reviewers sign off"),
                   ("eff", "Effective", "New version applied"), ("done", "Done", "Old version archived")],
        "path": ["new", "prog", "appr", "eff", "done"],
        "branches": [("appr", "prog", "Rejected: changes requested")],
        "handoffs": [("eff", "mrp", "Manufacturing uses the new BoM"), ("prog", "documents", "Drawings attached"), ("appr", "approvals", "Approval by the right team")],
        "auto": ["BoM versions and revision history", "Approval stages per change type", "Effective date for the switch"]},
    "purchase": {"record": "purchase order", "article": "a",
        "states": [("rfq", "RFQ", "From a reordering rule or by hand"), ("sent", "RFQ sent", "Vendor confirms price and date"),
                   ("po", "Purchase order", "Confirmed"), ("recv", "Received", "Receipt validated"), ("bill", "Billed", "Vendor bill matched")],
        "path": ["rfq", "sent", "po", "recv", "bill"],
        "branches": [("sent", "rfq", "Better price from another vendor"), ("recv", "po", "Partial receipt: backorder")],
        "handoffs": [("po", "stock", "Receipt expected"), ("bill", "account", "Bill posted to payables"), ("po", "approvals", "Approval above a set amount")],
        "auto": ["Vendor pricelists and lead times", "3-way match: order, receipt, bill", "Purchase agreements and tenders"]},
    "maintenance": {"record": "maintenance request", "article": "a",
        "states": [("new", "New request", "Reported by an operator"), ("plan", "Scheduled", "Technician and date set"), ("prog", "In progress", "Work on the equipment"),
                   ("rep", "Repaired", "Back in service"), ("close", "Closed", "Downtime recorded")],
        "path": ["new", "plan", "prog", "rep", "close"],
        "branches": [("prog", "close", "Beyond repair: scrapped"), ("close", "plan", "Preventive: next date planned")],
        "handoffs": [("prog", "stock", "Spare parts used"), ("new", "mrp", "Work centre blocked"), ("close", "spreadsheet_dashboard", "MTBF and downtime")],
        "auto": ["Preventive maintenance by date or usage", "Equipment per work centre", "Maintenance teams and calendars"]},
    "quality_control": {"record": "quality check", "article": "a",
        "states": [("point", "Control point", "On a product or operation"), ("check", "Check", "Pass/fail, measure or photo"), ("alert", "Alert", "Raised on a failure"),
                   ("act", "Corrective action", "Root cause and fix"), ("closed", "Closed", "Solved and recorded")],
        "path": ["point", "check", "alert", "act", "closed"],
        "branches": [("check", "closed", "Passed: nothing to do")],
        "handoffs": [("check", "stock", "Receipts and deliveries checked"), ("check", "mrp", "Work order checks"), ("alert", "maintenance", "Equipment issue logged")],
        "auto": ["Control points by product, operation or work centre", "Measurement tolerances", "Quality alerts with teams and stages"]},
    # ------------------------------------------------------------------ HR
    "hr": {"record": "employee", "article": "an",
        "states": [("hire", "Hired", "From Recruitment"), ("onb", "Onboarding", "Plan of activities"), ("act", "Active", "Contract and schedule"),
                   ("chg", "Changes", "Role, team or contract updated"), ("off", "Offboarding", "Plan and access removed")],
        "path": ["hire", "onb", "act", "chg", "off"],
        "branches": [("chg", "act", "Promotion: new contract")],
        "handoffs": [("onb", "hr_holidays", "Leave allocation"), ("act", "hr_payroll", "Payroll from the contract"), ("off", "fleet", "Company car returned")],
        "auto": ["Onboarding and offboarding plans", "Org chart and departments", "Documents on the employee record"]},
    "hr_recruitment": {"record": "applicant", "article": "an",
        "states": [("new", "New", "Applied from the job page"), ("qual", "Initial qualification", "CV reviewed"), ("int1", "First interview", "Scheduled from the record"),
                   ("int2", "Second interview", "Team interview"), ("prop", "Contract proposal", "Offer sent"), ("sign", "Contract signed", "Hired")],
        "path": ["new", "qual", "int1", "int2", "prop", "sign"],
        "branches": [("qual", "new", "Refused: kept in the talent pool"), ("int2", "int1", "Needs another interview")],
        "handoffs": [("sign", "hr", "Employee created"), ("prop", "sign", "Offer signed online"), ("int1", "mail", "Interview invitation sent")],
        "auto": ["Job pages that receive applications", "Stages per job", "Email templates for every stage"]},
    "hr_holidays": {"record": "time-off request", "article": "a",
        "states": [("sub", "To submit", "Employee picks dates"), ("appr", "To approve", "Manager notified"), ("second", "Second approval", "HR, where needed"),
                   ("ok", "Approved", "On the team calendar"), ("taken", "Taken", "Deducted from the allocation")],
        "path": ["sub", "appr", "second", "ok", "taken"],
        "branches": [("appr", "sub", "Refused with a reason")],
        "handoffs": [("ok", "hr_payroll", "Unpaid leave in payroll"), ("ok", "planning", "Shifts blocked"), ("appr", "mail", "Notification to the manager")],
        "auto": ["Accrual plans for allocations", "Approval by manager or HR", "Public holidays per country"]},
    "hr_appraisal": {"record": "appraisal", "article": "an",
        "states": [("start", "To start", "Scheduled from the plan"), ("sent", "Appraisal sent", "Forms to employee and manager"), ("self", "Self-assessment", "Employee's view"),
                   ("mgr", "Manager review", "Manager's view"), ("done", "Done", "Goals set for next period")],
        "path": ["start", "sent", "self", "mgr", "done"],
        "branches": [("mgr", "self", "Discussion: revised together")],
        "handoffs": [("done", "hr", "Skills and goals updated on the employee"), ("sent", "survey", "Feedback forms from colleagues")],
        "auto": ["Appraisal plans after hiring and yearly", "Goals and skills", "360 feedback from colleagues"]},
    "hr_referral": {"record": "referral", "article": "a",
        "states": [("share", "Shared", "Job shared by an employee"), ("apply", "Applied", "Friend applies"), ("prog", "In progress", "Moves through recruitment"),
                   ("hired", "Hired", "Referral successful"), ("reward", "Rewarded", "Points and rewards")],
        "path": ["share", "apply", "prog", "hired", "reward"],
        "branches": [("prog", "apply", "Not hired: points kept")],
        "handoffs": [("apply", "hr_recruitment", "Applicant with the referrer"), ("share", "social", "Shared on social")],
        "auto": ["Points per stage", "Rewards shop", "Share links per employee"]},
    "fleet": {"record": "vehicle", "article": "a",
        "states": [("req", "New request", "Vehicle needed for a role"), ("ord", "To order", "Model and contract chosen"), ("reg", "Registered", "Assigned to a driver"),
                   ("down", "Downgraded", "End of contract, returned")],
        "path": ["req", "ord", "reg", "down"],
        "branches": [("reg", "reg", "Service and costs logged"), ("reg", "ord", "Replacement ordered")],
        "handoffs": [("reg", "hr", "Driver is an employee"), ("reg", "account", "Service bills posted"), ("ord", "documents", "Contract documents filed")],
        "auto": ["Contract renewal reminders", "Odometer and fuel logs", "Cost analysis per vehicle"]},
    "hr_payroll": {"record": "payslip batch", "article": "a",
        "states": [("draft", "Draft", "From contracts and schedules"), ("comp", "Computed", "Salary rules applied"), ("wait", "Waiting", "Warnings reviewed"),
                   ("done", "Done", "Journal entry posted"), ("paid", "Paid", "Bank payment made")],
        "path": ["draft", "comp", "wait", "done", "paid"],
        "branches": [("wait", "comp", "Correction: recomputed")],
        "handoffs": [("done", "accountant", "Salaries and liabilities booked"), ("draft", "hr_holidays", "Unpaid leave taken into account"), ("paid", "hr", "Payslips on the employee")],
        "auto": ["Salary structures by country where Odoo provides them", "Test print of a pay run", "Net-to-gross simulation"]},
    # ------------------------------------------------------------------ marketing
    "social": {"record": "social post", "article": "a",
        "states": [("draft", "Draft", "One post for several accounts"), ("sched", "Scheduled", "Date and time set"), ("pub", "Published", "Live on each network"),
                   ("eng", "Engagement", "Comments and reactions in the stream"), ("lead", "Leads", "Clicks tracked to CRM")],
        "path": ["draft", "sched", "pub", "eng", "lead"],
        "branches": [("eng", "eng", "Reply from the stream")],
        "handoffs": [("lead", "crm", "Leads with the post as source"), ("pub", "website", "Visitors tracked on the site")],
        "auto": ["Scheduling across accounts", "Streams per network", "UTM tracking on links"]},
    "mass_mailing": {"record": "mailing", "article": "a",
        "states": [("draft", "Draft", "Template and mailing list"), ("test", "Tested", "Test sent, A/B split set"), ("sent", "Sent", "Delivered to the list"),
                   ("open", "Opened", "Opens and clicks tracked"), ("conv", "Converted", "Leads or orders")],
        "path": ["draft", "test", "sent", "open", "conv"],
        "branches": [("sent", "sent", "Bounced: contact flagged"), ("open", "test", "A/B winner sent to the rest")],
        "handoffs": [("conv", "crm", "Opportunities from the mailing"), ("conv", "sale", "Orders attributed"), ("open", "marketing_automation", "Follow-up campaign")],
        "auto": ["Mailing lists and blacklist", "A/B testing with a winner", "UTM and revenue attribution"]},
    "mass_mailing_sms": {"record": "SMS campaign", "article": "an",
        "states": [("draft", "Draft", "Short message and list"), ("sent", "Sent", "Credits used per message"), ("dlv", "Delivered", "Delivery reports"),
                   ("click", "Clicked", "Short links tracked"), ("conv", "Converted", "Lead or order")],
        "path": ["draft", "sent", "dlv", "click", "conv"],
        "branches": [("sent", "sent", "Invalid number: excluded next time")],
        "handoffs": [("conv", "crm", "Lead from the SMS"), ("click", "website", "Visit tracked")],
        "auto": ["Opt-out handling", "Link tracking", "Lists shared with email marketing"]},
    "event": {"record": "event registration", "article": "an",
        "states": [("pub", "Published", "Event page with tickets"), ("reg", "Registered", "Ticket booked or bought"), ("conf", "Confirmed", "Reminder emails"),
                   ("att", "Attended", "Badge scanned at the door"), ("fol", "Followed up", "Leads for sales")],
        "path": ["pub", "reg", "conf", "att", "fol"],
        "branches": [("reg", "reg", "Sold out: waiting list"), ("conf", "pub", "Cancelled: seat released")],
        "handoffs": [("reg", "website_sale", "Paid tickets"), ("fol", "crm", "Leads from attendees"), ("conf", "mass_mailing", "Reminders")],
        "auto": ["Ticket types and seats", "Scheduled communications", "Badge printing and scanning"]},
    "marketing_automation": {"record": "campaign participant", "article": "a",
        "states": [("in", "Entered", "Matches the campaign filter"), ("act1", "First email", "Sent on entry"), ("wait", "Waiting", "Trigger or delay"),
                   ("act2", "Next step", "Depends on what they did"), ("out", "Completed", "Converted or finished")],
        "path": ["in", "act1", "wait", "act2", "out"],
        "branches": [("wait", "act2", "Opened: sales follow-up"), ("wait", "act1", "Not opened: resend with a new subject")],
        "handoffs": [("act2", "crm", "Opportunity for a salesperson"), ("act1", "mass_mailing", "Emails from templates"), ("act2", "mass_mailing_sms", "SMS step")],
        "auto": ["Triggers: opened, clicked, replied, not opened", "Test mode on real data", "Server actions as steps"]},
    "survey": {"record": "survey response", "article": "a",
        "states": [("pub", "Published", "Link or invitation"), ("start", "Started", "Participant begins"), ("done", "Completed", "Answers saved"),
                   ("score", "Scored", "Points or certification"), ("act", "Actioned", "Results used")],
        "path": ["pub", "start", "done", "score", "act"],
        "branches": [("start", "pub", "Abandoned: reminder sent")],
        "handoffs": [("act", "crm", "Lead from a qualifying answer"), ("score", "website_slides", "Certification for a course"), ("act", "hr_appraisal", "Feedback for an appraisal")],
        "auto": ["Scoring and certifications", "Conditional questions", "Live sessions for events"]},
    # ------------------------------------------------------------------ services
    "project": {"record": "task", "article": "a",
        "states": [("new", "New", "From a sales order, email or by hand"), ("prog", "In progress", "Assignee and deadline"), ("chg", "Changes requested", "Customer or reviewer asks"),
                   ("appr", "Approved", "Signed off"), ("done", "Done", "Milestone reached")],
        "path": ["new", "prog", "chg", "appr", "done"],
        "branches": [("chg", "prog", "Reworked"), ("prog", "prog", "Blocked by another task")],
        "handoffs": [("done", "sale", "Milestone invoiced"), ("prog", "hr_timesheet", "Time logged"), ("new", "planning", "Scheduled in Planning")],
        "auto": ["Stages and task dependencies", "Customer portal and ratings", "Recurring tasks"]},
    "hr_timesheet": {"record": "timesheet", "article": "a",
        "states": [("log", "Logged", "Timer or grid"), ("sub", "Submitted", "Week sent"), ("val", "Validated", "Manager approves"),
                   ("bill", "Billable", "Linked to a sales order line"), ("inv", "Invoiced", "On the next invoice")],
        "path": ["log", "sub", "val", "bill", "inv"],
        "branches": [("val", "log", "Corrected before validation")],
        "handoffs": [("bill", "sale", "Delivered quantity on the order"), ("inv", "account", "Invoice posted"), ("val", "project", "Project profitability")],
        "auto": ["Timers on tasks", "Validation by manager", "Billable rates per employee or service"]},
    "industry_fsm": {"record": "field service task", "article": "a",
        "states": [("new", "New", "From a sales order or ticket"), ("plan", "Planned", "Technician and slot set"), ("site", "On site", "Worksheet filled"),
                   ("sign", "Signed", "Customer signs on the phone"), ("inv", "Invoiced", "Time and parts billed")],
        "path": ["new", "plan", "site", "sign", "inv"],
        "branches": [("site", "plan", "Parts missing: second visit")],
        "handoffs": [("plan", "planning", "Odoo 20 runs this in Planning"), ("site", "stock", "Parts used from the van"), ("inv", "account", "Invoice posted")],
        "auto": ["Worksheets per service", "Routes and maps (in Planning from Odoo 20)", "Customer signature on site"]},
    "helpdesk": {"record": "ticket", "article": "a",
        "states": [("new", "New", "Email, form, chat or phone"), ("prog", "In progress", "Assigned by rule"), ("hold", "On hold", "Waiting on the customer"),
                   ("solved", "Solved", "Answer or fix sent"), ("rated", "Rated", "Customer rates the reply")],
        "path": ["new", "prog", "hold", "solved", "rated"],
        "branches": [("prog", "prog", "SLA at risk: escalated"), ("solved", "prog", "Reopened by the customer")],
        "handoffs": [("prog", "stock", "Return or replacement"), ("prog", "account", "Refund or credit note"), ("solved", "knowledge", "Answer saved as an article")],
        "auto": ["SLA policies by priority and team", "Assignment: balanced or random", "Email aliases per team"]},
    "planning": {"record": "shift", "article": "a",
        "states": [("open", "Open", "Shift from a template"), ("assign", "Assigned", "To a person with the role"), ("pub", "Published", "Sent to the team"),
                   ("done", "Done", "Worked and timed")],
        "path": ["open", "assign", "pub", "done"],
        "branches": [("assign", "open", "Conflict with time off: unassigned"), ("pub", "assign", "Swap requested: reassigned")],
        "handoffs": [("pub", "mail", "Schedule sent"), ("done", "hr_timesheet", "Time from the shift"), ("assign", "hr_holidays", "Time off checked")],
        "auto": ["Templates and recurring shifts", "Roles and skills", "Field service map and routes from Odoo 20"]},
    "appointment": {"record": "appointment", "article": "an",
        "states": [("page", "Booking page", "Services and staff"), ("slot", "Slot chosen", "From live availability"), ("conf", "Confirmed", "Invitation and video link"),
                   ("rem", "Reminded", "Email or SMS reminder"), ("att", "Attended", "Meeting held")],
        "path": ["page", "slot", "conf", "rem", "att"],
        "branches": [("conf", "slot", "Rescheduled by the customer"), ("rem", "rem", "No-show recorded")],
        "handoffs": [("conf", "crm", "Lead or opportunity"), ("att", "account", "Paid booking invoiced"), ("conf", "mail", "Calendar invite")],
        "auto": ["Availability by staff and resource", "Questions before booking", "Online payment for paid slots"]},
    # ------------------------------------------------------------------ productivity
    "mail": {"record": "message", "article": "a",
        "states": [("post", "Posted", "In a channel or on a record"), ("men", "Mentioned", "@person notified"), ("act", "Activity", "Scheduled with a deadline"),
                   ("done", "Done", "Marked done, feedback logged"), ("hist", "History", "Kept in the chatter")],
        "path": ["post", "men", "act", "done", "hist"],
        "branches": [("act", "act", "Overdue: shown in red")],
        "handoffs": [("post", "crm", "Chatter on the opportunity"), ("act", "project", "Task follow-up"), ("men", "voip", "Call back")],
        "auto": ["Activity types with default deadlines", "Channels per team", "Email in and out of the chatter"]},
    "approvals": {"record": "approval request", "article": "an",
        "states": [("new", "To submit", "Category with its rules"), ("sub", "Submitted", "Approvers notified"),
                   ("appr", "Approved", "The required approvers agreed"), ("done", "Done", "Order or payment made")],
        "path": ["new", "sub", "appr", "done"],
        "branches": [("sub", "new", "Refused: reason sent back")],
        "handoffs": [("done", "purchase", "Purchase order created"), ("sub", "mail", "Approvers notified"), ("appr", "account", "Payment approved")],
        "auto": ["Minimum approvers per category", "Approval order", "Documents required before submitting"]},
    "iot": {"record": "device reading", "article": "a",
        "states": [("dev", "Device", "Scale, printer, scanner or terminal"), ("box", "IoT box", "Connects devices to Odoo"), ("read", "Reading", "Weight, scan or payment"),
                   ("app", "In the app", "Used on the operation"), ("log", "Recorded", "Stored on the record")],
        "path": ["dev", "box", "read", "app", "log"],
        "branches": [("read", "dev", "Device offline: retry")],
        "handoffs": [("app", "point_of_sale", "Payment terminal and printer"), ("app", "mrp", "Measurements on work orders"), ("app", "quality_control", "Quality measurements")],
        "auto": ["Device auto-detection", "Triggers on work orders", "Printers per operation"]},
    "voip": {"record": "call", "article": "a",
        "states": [("ring", "Incoming", "Number matched to a contact"), ("talk", "Answered", "Record opens on screen"), ("note", "Logged", "Notes on the chatter"),
                   ("act", "Follow-up", "Activity scheduled"), ("done", "Closed", "Next step done")],
        "path": ["ring", "talk", "note", "act", "done"],
        "branches": [("ring", "act", "Missed: call-back activity")],
        "handoffs": [("talk", "crm", "Opportunity opened"), ("talk", "helpdesk", "Ticket opened"), ("act", "mail", "Activity in the chatter")],
        "auto": ["Click to call from any record", "Call queues from activities", "Call history per contact"]},
    "knowledge": {"record": "article", "article": "an",
        "states": [("draft", "Draft", "Written with templates"), ("rev", "Reviewed", "Shared with editors"), ("pub", "Published", "Workspace or public"),
                   ("emb", "Embedded", "Linked from records and tickets"), ("upd", "Updated", "Versions kept")],
        "path": ["draft", "rev", "pub", "emb", "upd"],
        "branches": [("upd", "rev", "Change reviewed again")],
        "handoffs": [("emb", "helpdesk", "Answers for tickets"), ("pub", "website", "Shared online"), ("emb", "project", "Procedures on tasks")],
        "auto": ["Nested workspaces", "Templates and embedded views", "Access per workspace"]},
    "whatsapp": {"record": "WhatsApp message", "article": "a",
        "states": [("tpl", "Template", "Approved by Meta"), ("sent", "Sent", "From a record or automation"), ("read", "Read", "Delivery and read status"),
                   ("reply", "Replied", "Conversation opens"), ("act", "Actioned", "Lead, ticket or order")],
        "path": ["tpl", "sent", "read", "reply", "act"],
        "branches": [("sent", "sent", "Failed: number not on WhatsApp")],
        "handoffs": [("act", "crm", "Lead from the chat"), ("act", "helpdesk", "Ticket from the chat"), ("sent", "sale", "Order confirmation sent")],
        "auto": ["Templates with variables", "Automated sends on events", "Conversations in Discuss"]},
    "ai_app": {"record": "AI request", "article": "an",
        "states": [("ask", "Asked", "From a record or a chat"), ("read", "Reads data", "Records the user may see"), ("draft", "Drafted", "Text, summary or fields"),
                   ("rev", "Reviewed", "A person checks it"), ("write", "Written back", "Saved on the record")],
        "path": ["ask", "read", "draft", "rev", "write"],
        "branches": [("rev", "draft", "Edited or regenerated")],
        "handoffs": [("write", "crm", "Lead fields filled"), ("write", "helpdesk", "Reply drafted"), ("read", "knowledge", "Answers from articles")],
        "auto": ["Access rights respected", "Prompts saved per use", "Human review before anything is sent"]},
}
