# -*- coding: utf-8 -*-
"""The homepage industries slide wears each industry page's own skin. Rather than load all eight world stylesheets on the
homepage, build.py calls write() to extract just what the slide uses (the world's variables, its title card .ixw-copy, its
Nexi Explains tag and its button family) from assets/css/worlds/<key>.css and the engine's base rules, rescoped from
.ixw--<key> / .ixw to .hxs--<key> / .hxs, into assets/css/hero-skins.css. hero-industries.js loads it when the page is idle.
Edit the worlds' CSS, never the generated file."""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
WORLDS = ["medical", "travel", "retail", "ecommerce", "construction", "fnb", "manufacturing", "health-wellness"]


def _split_top(sel):
    out, depth, cur = [], 0, ""
    for ch in sel:
        if ch in "([": depth += 1
        elif ch in ")]": depth -= 1
        if ch == "," and depth == 0: out.append(cur.strip()); cur = ""
        else: cur += ch
    if cur.strip(): out.append(cur.strip())
    return out


def _blocks(css):
    """Top-level (prelude, body) pairs; comments removed."""
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    out, i, n = [], 0, len(css)
    while i < n:
        j = css.find("{", i)
        if j < 0: break
        pre, depth, k = css[i:j].strip(), 1, j + 1
        while k < n and depth:
            if css[k] == "{": depth += 1
            elif css[k] == "}": depth -= 1
            k += 1
        out.append((pre, css[j + 1:k - 1])); i = k
    return out


def _rule(pre, body, mapper):
    sels = [m for m in (mapper(s) for s in _split_top(pre)) if m]
    return (",".join(sels) + "{" + body.strip() + "}") if sels else ""


def _walk(css, mapper, keep_frames=True):
    out = []
    for pre, body in _blocks(css):
        if pre.startswith("@media") or pre.startswith("@supports"):
            inner = "".join(r for r in (_rule(p, b, mapper) for p, b in _blocks(body)) if r)
            if inner: out.append(pre + "{" + inner + "}")
        elif pre.startswith("@keyframes"):
            if keep_frames: out.append(pre + "{" + body.strip() + "}")
        elif not pre.startswith("@"):
            r = _rule(pre, body, mapper)
            if r: out.append(r)
    return out


def _world_mapper(k):
    w = ".ixw--" + k
    def m(s):
        if s == w: return ".hxs--" + k
        if s.startswith(w + " main "):
            rest = s[len(w + " main "):]
            return (".hxs--" + k + " " + rest) if ".btn" in rest and ".ixw-cta" not in rest.split(":is(")[0] else None
        if s.startswith(w + " .ixw-copy"):
            return ".hxs--" + k + s[len(w):].replace(" h1", " .hxs-h")
        if s.startswith(w + " .ixw-ep-tag") or s.startswith(w + " .h1-hand"):
            return ".hxs--" + k + s[len(w):]
        return None
    return m


def _engine_mapper(s):
    if s == ".ixw": return ".hxs"
    if s.startswith(".ixw .btn"): return ".hxs" + s[4:]
    if s.startswith(".ixw .hand"): return ".hxs" + s[4:]
    if re.match(r"\.ixw-(ep|ep-tag|hint)\b", s): return ".hxs " + s
    if s.startswith(".ixw-copy"): return ".hxs " + s.replace(" h1", " .hxs-h")
    return None


def build():
    eng = (ROOT / "assets/css/industry-world.css").read_text(encoding="utf-8")
    parts = ["/* GENERATED by _src/hero_skins.py from the industry stylesheets. Do not edit. */"]
    # the engine's base: variables, the lip button family, the episode tag, the hint, the card (no keyframes but the twinkle)
    parts += [r for r in _walk(eng, _engine_mapper, keep_frames=False)]
    parts += [f for f in re.findall(r"@keyframes ixwTwinkle\{.*?\}\}", eng, re.S)]
    for k in WORLDS:
        css = (ROOT / "assets/css/worlds" / f"{k}.css").read_text(encoding="utf-8")
        rules = _walk(css, _world_mapper(k))
        # the bare world block: variables only
        rules = [re.sub(r"^(\.hxs--[a-z-]+)\{(.*)\}$", lambda m: m.group(1) + "{" + ";".join(d for d in m.group(2).split(";") if d.strip().startswith("--")) + "}", r, flags=re.S)
                 if re.match(r"^\.hxs--[a-z-]+\{", r) else r for r in rules]
        parts.append(f"/* {k} */")
        parts += [r for r in rules if not r.endswith("{}")]
    return "\n".join(parts) + "\n"


def write():
    out = ROOT / "assets/css/hero-skins.css"
    css = build()
    if not out.exists() or out.read_text(encoding="utf-8") != css:
        out.write_text(css, encoding="utf-8")
    return len(css)


if __name__ == "__main__":
    print(write(), "bytes")
