"""Nexi, TechNext's AI companion: the full chatbot page.

Source: _src/nexi/app.html (the Nexi concept page: 3D robot, chat panel, knowledge base, mini tours)
and _src/nexi/icons.json. build.py calls:

  write_js()          before the asset hash: splits the page's script into assets/js/nexi-app.js
                      (icons inlined, logos from assets/img/)
  write_page(v, idx)  after the pages are built: writes nexi-app.html, the frame page that /nexi
                      embeds, with the site's page index as a JSON data block so Nexi can point to
                      any page, including new ones

The CSP only allows same-origin scripts, so Three.js comes from assets/js/vendor/. nexi-app.html is
noindex and not in the sitemap; opened on its own it forwards to /nexi.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(__file__).resolve().parent / "nexi"
THREE_CDN = '<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>'
FONTS = re.compile(r'<link rel="preconnect"[^>]*>\s*<link rel="preconnect"[^>]*>\s*<link rel="stylesheet" href="https://fonts\.googleapis\.com[^"]*">')


def _parts():
    html = (SRC / "app.html").read_text(encoding="utf-8")
    style = re.search(r"<style>.*?</style>", html, re.S).group(0)
    markup = html[html.index("</style>") + len("</style>"):html.index(THREE_CDN)].strip()
    script = html[html.index(THREE_CDN) + len(THREE_CDN):]
    script = script[script.index("<script>") + len("<script>"):script.rindex("</script>")].strip()
    fonts = FONTS.search(html).group(0)
    return fonts, style, markup, script


def _js(script: str) -> str:
    icons = json.loads((SRC / "icons.json").read_text(encoding="utf-8"))
    reps = [
        ('var SITE_URL = "https://technext.asia/";', 'var SITE_URL = "/";'),
        ("var ICONS = __ICONS__;", "var ICONS = " + json.dumps(icons, ensure_ascii=False) + ";"),
        ("var SITE = __SITE__;",
         'var SITE = (function(){ try { return JSON.parse(document.getElementById("nexi-site").textContent); } catch (e) { return []; } })();'),
        ("window.__NEXI_LOGO__", '"assets/img/logo-plane.png"'),
    ]
    for a, b in reps:
        assert script.count(a) == 1, a
        script = script.replace(a, b)
    for token in ("__ICONS__", "__SITE__", "__NEXI_LOGO__", "__LOGO_"):
        assert token not in script, token
    head = ("/* Nexi, TechNext's AI companion (the full chatbot on /nexi). Generated by _src/make_nexi.py from\n"
            "   _src/nexi/app.html - edit that file, then run python _src/build.py. */\n")
    # the page only runs inside /nexi; opened on its own it forwards there
    guard = 'if (window.top === window.self) { location.replace("/nexi"); return; }\n'
    return head + script.replace('"use strict";', '"use strict";\n' + guard, 1) + "\n"


def write_js():
    _, _, _, script = _parts()
    out = ROOT / "assets" / "js" / "nexi-app.js"
    js = _js(script)
    if not out.exists() or out.read_text(encoding="utf-8") != js:
        out.write_text(js, encoding="utf-8", newline="\n")


def write_page(asset_v: str, index: list, site_url: str):
    fonts, style, markup, _ = _parts()
    markup = (markup.replace("__LOGO_PLANE__", "assets/img/logo-plane.png")
                    .replace("__LOGO_TEXT__", "assets/img/logo-text.png")
                    .replace("__LOGO_H__", "assets/img/logo-horizontal.png"))
    data = json.dumps(sorted(index, key=lambda e: e["u"]), ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="robots" content="noindex">
<title>Nexi, TechNext's AI companion</title>
<link rel="canonical" href="{site_url}nexi">
{fonts}
{style}
</head>
<body>
{markup}
<script type="application/json" id="nexi-site">{data}</script>
<script src="assets/js/vendor/three-r128.min.js"></script>
<script src="assets/js/nexi-app.js?v={asset_v}"></script>
</body>
</html>
"""
    (ROOT / "nexi-app.html").write_text(html, encoding="utf-8", newline="\n")
